"""Tests for the third-party notices renderer."""

from __future__ import annotations

from license_audit.core.models import (
    AnalysisReport,
    LicenseCategory,
    LicenseSource,
    PackageLicense,
)
from license_audit.reports.notices import NoticesRenderer


def _make_pkg(
    name: str = "some-pkg",
    version: str = "1.0.0",
    license_expression: str = "MIT",
    category: LicenseCategory = LicenseCategory.PERMISSIVE,
    license_text: str | None = None,
) -> PackageLicense:
    return PackageLicense(
        name=name,
        version=version,
        license_expression=license_expression,
        license_source=LicenseSource.PEP639,
        category=category,
        license_text=license_text,
    )


class TestNoticesRenderer:
    def test_contains_header_and_footer(self) -> None:
        report = AnalysisReport(
            project_name="my-project",
            packages=[_make_pkg()],
        )
        renderer = NoticesRenderer()
        result = renderer.render(report)
        assert "# Third-Party Notices" in result
        assert "my-project" in result
        assert "Generated by" in result

    def test_package_section_without_license_text(self) -> None:
        report = AnalysisReport(
            project_name="my-project",
            packages=[_make_pkg(name="click", version="8.1.0")],
        )
        renderer = NoticesRenderer()
        result = renderer.render(report)
        assert "## click 8.1.0" in result
        assert "**License:** MIT" in result
        assert "License text not available" in result

    def test_package_section_with_license_text(self) -> None:
        report = AnalysisReport(
            project_name="my-project",
            packages=[
                _make_pkg(
                    name="fake_pkg",
                    version="1.0.0",
                    license_text="Copyright 2024 Fake Corp\nMIT License",
                )
            ],
        )
        renderer = NoticesRenderer()
        result = renderer.render(report)
        assert "Copyright 2024 Fake Corp" in result
        assert "MIT License" in result
        assert "License text not available" not in result

    def test_packages_sorted_by_name(self) -> None:
        report = AnalysisReport(
            project_name="my-project",
            packages=[
                _make_pkg(name="z-pkg"),
                _make_pkg(name="a-pkg"),
                _make_pkg(name="m-pkg"),
            ],
        )
        renderer = NoticesRenderer()
        result = renderer.render(report)
        a_pos = result.index("## a-pkg")
        m_pos = result.index("## m-pkg")
        z_pos = result.index("## z-pkg")
        assert a_pos < m_pos < z_pos

    def test_empty_report(self) -> None:
        renderer = NoticesRenderer()
        result = renderer.render(AnalysisReport())
        assert "# Third-Party Notices" in result

    def test_source_in_header(self) -> None:
        report = AnalysisReport(project_name="p", source="/abs/.venv")
        result = NoticesRenderer().render(report)
        assert "Source: /abs/.venv" in result
