"""Tests for PoetryLockSource."""

from __future__ import annotations

from pathlib import Path

import pytest

from license_audit.sources.poetry_lock import PoetryLockSource

# Synthetic poetry.lock 2.x with main + dev + custom group + git source.
_SYNTHETIC_LOCK_V2 = """\
# This file is automatically @generated by Poetry and should not be changed by hand.

[[package]]
name = "click"
version = "8.1.7"
description = "..."
optional = false
python-versions = ">=3.7"
groups = ["main"]

[[package]]
name = "ipython"
version = "8.28.0"
description = "..."
optional = false
python-versions = ">=3.10"
groups = ["dev"]

[[package]]
name = "pytest"
version = "8.3.3"
description = "..."
optional = false
python-versions = ">=3.8"
groups = ["test"]

[[package]]
name = "shared-pkg"
version = "1.0.0"
description = "Used by both main and dev"
optional = false
python-versions = ">=3.8"
groups = ["main", "dev"]

[[package]]
name = "git-pkg"
version = "0.1.0"
description = "Pulled from git"
optional = false
python-versions = ">=3.8"
groups = ["main"]

[package.source]
type = "git"
url = "https://github.com/example/git-pkg.git"
reference = "main"
resolved_reference = "abc123def456"

[metadata]
lock-version = "2.1"
python-versions = ">=3.10"
content-hash = "deadbeef"
"""


_SYNTHETIC_LOCK_V1 = """\
[[package]]
name = "click"
version = "8.1.7"
description = "..."
category = "main"
optional = false
python-versions = ">=3.7"

[[package]]
name = "pytest"
version = "8.3.3"
description = "..."
category = "dev"
optional = false
python-versions = ">=3.8"

[metadata]
lock-version = "1.1"
python-versions = "^3.10"
content-hash = "deadbeef"
"""


class TestPoetryLockSource:
    def test_parse_synthetic(self, tmp_path: Path) -> None:
        lock_file = tmp_path / "poetry.lock"
        lock_file.write_text(_SYNTHETIC_LOCK_V2)
        source = PoetryLockSource(lock_file)
        specs = source.parse()
        names = {s.name for s in specs}
        assert names == {"click", "ipython", "pytest", "shared_pkg", "git_pkg"}

    def test_pinned_versions(self, tmp_path: Path) -> None:
        lock_file = tmp_path / "poetry.lock"
        lock_file.write_text(_SYNTHETIC_LOCK_V2)
        source = PoetryLockSource(lock_file)
        for spec in source.parse():
            assert spec.version_constraint.startswith("=="), (
                f"{spec.name} not pinned: {spec.version_constraint}"
            )

    def test_missing_file(self, tmp_path: Path) -> None:
        source = PoetryLockSource(tmp_path / "poetry.lock")
        with pytest.raises(FileNotFoundError):
            source.parse()

    def test_unsupported_lock_version(self, tmp_path: Path) -> None:
        lock_file = tmp_path / "poetry.lock"
        lock_file.write_text(
            '[metadata]\nlock-version = "9.0"\npython-versions = "*"\n'
            'content-hash = "x"\n'
        )
        source = PoetryLockSource(lock_file)
        with pytest.raises(ValueError, match=r"Unsupported poetry\.lock version"):
            source.parse()

    def test_missing_metadata(self, tmp_path: Path) -> None:
        lock_file = tmp_path / "poetry.lock"
        lock_file.write_text("# empty\n")
        source = PoetryLockSource(lock_file)
        with pytest.raises(ValueError, match=r"missing \[metadata\] section"):
            source.parse()

    def test_optional_selector_raises(self, tmp_path: Path) -> None:
        lock_file = tmp_path / "poetry.lock"
        lock_file.write_text(_SYNTHETIC_LOCK_V2)
        source = PoetryLockSource(lock_file, groups=["optional:docs"])
        with pytest.raises(ValueError, match=r"optional:docs"):
            source.parse()


class TestPoetryLockSourceGroupFiltering:
    def _names(self, tmp_path: Path, groups: list[str] | None) -> set[str]:
        lock_file = tmp_path / "poetry.lock"
        lock_file.write_text(_SYNTHETIC_LOCK_V2)
        source = PoetryLockSource(lock_file, groups=groups)
        return {s.name for s in source.parse()}

    def test_none_includes_all(self, tmp_path: Path) -> None:
        names = self._names(tmp_path, None)
        assert names == {"click", "ipython", "pytest", "shared_pkg", "git_pkg"}

    def test_main_only(self, tmp_path: Path) -> None:
        names = self._names(tmp_path, ["main"])
        assert names == {"click", "shared_pkg", "git_pkg"}

    def test_dev_selector(self, tmp_path: Path) -> None:
        names = self._names(tmp_path, ["dev"])
        assert names == {"ipython", "shared_pkg"}

    def test_group_test(self, tmp_path: Path) -> None:
        names = self._names(tmp_path, ["group:test"])
        assert names == {"pytest"}

    def test_main_and_group_test(self, tmp_path: Path) -> None:
        names = self._names(tmp_path, ["main", "group:test"])
        assert names == {"click", "shared_pkg", "git_pkg", "pytest"}

    def test_excludes_unselected(self, tmp_path: Path) -> None:
        names = self._names(tmp_path, ["main"])
        assert "ipython" not in names
        assert "pytest" not in names

    def test_package_in_multiple_groups_included_for_either(
        self, tmp_path: Path
    ) -> None:
        # shared_pkg is in both main and dev: should appear for either selector.
        for selector in (["main"], ["dev"]):
            assert "shared_pkg" in self._names(tmp_path, selector)


class TestPoetryLockBackcompat:
    def test_lock_v1_category_fallback(self, tmp_path: Path) -> None:
        lock_file = tmp_path / "poetry.lock"
        lock_file.write_text(_SYNTHETIC_LOCK_V1)
        source = PoetryLockSource(lock_file, groups=["dev"])
        names = {s.name for s in source.parse()}
        assert names == {"pytest"}

    def test_lock_v1_main_fallback(self, tmp_path: Path) -> None:
        lock_file = tmp_path / "poetry.lock"
        lock_file.write_text(_SYNTHETIC_LOCK_V1)
        source = PoetryLockSource(lock_file, groups=["main"])
        names = {s.name for s in source.parse()}
        assert names == {"click"}

    def test_lock_with_neither_groups_nor_category_defaults_to_main(
        self, tmp_path: Path
    ) -> None:
        lock_file = tmp_path / "poetry.lock"
        lock_file.write_text(
            '[[package]]\nname = "foo"\nversion = "1.0.0"\n'
            'optional = false\npython-versions = "*"\n\n'
            '[metadata]\nlock-version = "2.0"\npython-versions = ">=3.10"\n'
            'content-hash = "x"\n'
        )
        source = PoetryLockSource(lock_file, groups=["main"])
        names = {s.name for s in source.parse()}
        assert names == {"foo"}


class TestPoetryLockGitSource:
    def test_resolved_reference_preferred(self, tmp_path: Path) -> None:
        lock_file = tmp_path / "poetry.lock"
        lock_file.write_text(_SYNTHETIC_LOCK_V2)
        source = PoetryLockSource(lock_file)
        specs = {s.name: s for s in source.parse()}
        git_spec = specs["git_pkg"]
        assert git_spec.source_url == (
            "git+https://github.com/example/git-pkg.git@abc123def456"
        )

    def test_falls_back_to_reference(self, tmp_path: Path) -> None:
        lock_file = tmp_path / "poetry.lock"
        lock_file.write_text("""\
[[package]]
name = "git-pkg"
version = "0.1.0"
optional = false
python-versions = ">=3.8"
groups = ["main"]

[package.source]
type = "git"
url = "https://github.com/example/git-pkg.git"
reference = "v1.0"

[metadata]
lock-version = "2.0"
python-versions = ">=3.10"
content-hash = "x"
""")
        source = PoetryLockSource(lock_file)
        specs = source.parse()
        assert len(specs) == 1
        assert specs[0].source_url == "git+https://github.com/example/git-pkg.git@v1.0"

    def test_directory_source_skipped(self, tmp_path: Path) -> None:
        lock_file = tmp_path / "poetry.lock"
        lock_file.write_text("""\
[[package]]
name = "local-pkg"
version = "0.1.0"
optional = false
python-versions = ">=3.8"
groups = ["main"]

[package.source]
type = "directory"
url = "../local"

[metadata]
lock-version = "2.0"
python-versions = ">=3.10"
content-hash = "x"
""")
        source = PoetryLockSource(lock_file)
        specs = source.parse()
        assert specs[0].source_url == ""


_FIXTURE = Path(__file__).parents[2] / "fixtures" / "poetry.lock"


class TestPoetryLockFixture:
    """Regression tests against a committed real-world poetry.lock fixture."""

    def test_parses_without_error(self) -> None:
        specs = PoetryLockSource(_FIXTURE).parse()
        assert len(specs) > 0

    def test_all_versions_pinned(self) -> None:
        for spec in PoetryLockSource(_FIXTURE).parse():
            assert spec.name
            assert spec.version_constraint.startswith("==")

    def test_main_filter_excludes_dev_and_test(self) -> None:
        names = {s.name for s in PoetryLockSource(_FIXTURE, groups=["main"]).parse()}
        assert "click" in names
        assert "ipython" not in names
        assert "pytest" not in names

    def test_group_test_returns_only_test_packages(self) -> None:
        names = {
            s.name for s in PoetryLockSource(_FIXTURE, groups=["group:test"]).parse()
        }
        assert names == {"pytest"}

    def test_git_source_url_uses_resolved_reference(self) -> None:
        specs = {s.name: s for s in PoetryLockSource(_FIXTURE).parse()}
        assert specs["git_pkg"].source_url == (
            "git+https://github.com/example/git-pkg.git@abc123def456789"
        )
